### ISSUE TITLE
I unintentionally created a duplicate at slack_sdk-feedstock

### ISSUE THREAD

**Issue by maresb** [conda-forge/slack-sdk-feedstock#7]
Unfortunately I somehow missed this feedstock and created this one:

https://github.com/conda-forge/slack_sdk-feedstock/

Do you know the proper procedure for cleaning this up? Can we add `slack_sdk` as an output here and delete my feedstock?

**Comment by xylar** [comment]
I would ask on Gitter for some help from @conda-forge/core on how to do that: https://gitter.im/conda-forge/conda-forge.github.io

**Comment by ocefpaf** [comment]
We should archive this feedstock and mark the packages created here as broken. Also, feel free to add yourself as a maintainer in the old one :smile: 

Are you OK with archiving it?

**Comment by xylar** [comment]
I see, it's been around for a few months already.  So, yes, there must be some packages expecting `slack_sdk` that would give us trouble.  @maresb, please make a PR to add that new output and also to add yourself to this feedstock as a maintainer.  @ocefpaf, please do archive https://github.com/conda-forge/slack_sdk-feedstock/.  Do you want @maresb to go through the process on https://github.com/conda-forge/conda-forge-repodata-patches-feedstock to mark the packages from that feedstock as broken?

**Comment by ocefpaf** [comment]
> Do you want @maresb to go through the process on https://github.com/conda-forge/conda-forge-repodata-patches-feedstock to mark the packages from that feedstock as broken?

If there are packages that are relying on it, no. Those packages will slowly require newer versions and we will need to make the change in them in the future, so let's not break them right now.

**Comment by maresb** [comment]
Thanks everyone for the feedback!

If I understand correctly, the process is to add an extra output here and archive my feedstock. I'll submit the PR tomorrow.

**Comment by xylar** [comment]
@maresb, I think that's correct.
