### ISSUE TITLE
@conda-forge-admin, please add bot automerge

### ISSUE THREAD

**Issue by maresb** [conda-forge/slack-sdk-feedstock#79]
### Additional comment:

@xylar, since there are no runtime dependencies besides `python` I think nothing can go wrong by enabling automerge. Do you agree?

**Comment by xylar** [comment]
@maresb, I don't love automerge.  I feel like it frequently costs me more time than it saves.  But we can give it a try again.

**Comment by maresb** [comment]
Good point, thanks!!!
